Categories DOCs
alkemyTech/OT107-Server pull request #102
Opened 2021-12-10 16:31 UTC by Bascur

2021-12-11 15:27 UTC, juanpabloch requested changes
con eso va a quedar de 10

2021-12-11 15:27 UTC, juanpabloch commented on routes/categories.js
> + *          400:
hola bascur en los errores ponemos solo la descripcion, porque no tenemos ningun esquema para devolver, de ultima una vez que hagamos el manejador de errores podemos documentar los errores mejor
saludos!!!!!

2021-12-11 15:27 UTC, juanpabloch commented on routes/categories.js
> + *             minimun: 1
typo, minimum

2021-12-11 15:27 UTC, juanpabloch commented on routes/categories.js
> + *              description: succes
typo, success

2021-12-11 15:27 UTC, juanpabloch commented on routes/categories.js
> + *                      schema: array
tenes mal armado el schema, y esta mal en todos, deberia quedar algo asi:
content:
 *                  application/json:
 *                      schema:
 *                          type: array
 *                          items:
 *                              $ref: '#components/schemes/members'

2021-12-11 15:27 UTC, juanpabloch commented on routes/categories.js
> + *                          $ref:'#components/schemes/categories'
y te falta un espacio despues de $ref: <espacio> en todos

2021-12-11 17:16 UTC, Bascur commented on routes/categories.js
> + *          400:
*          400:
 *              description: invalid token
 *          401:
 *              description: access denied

2021-12-11 17:17 UTC, Bascur commented on routes/categories.js
> + *                      schema: array
*              content:
 *                  application/json:
 *                      schema: 
 *                         type: array
 *                         items:
 *                            $ref:' #components/schemes/categories'

2021-12-12 00:25 UTC, acmaccan commented on routes/categories.js
> + * schemes:
Bascur! Estuvimos viendo con los chicos, acá va schemas

2021-12-12 00:26 UTC, acmaccan commented on routes/categories.js
> + *                            $ref:' #components/schemes/categories'
En todos los $ref va schemas

2021-12-12 00:27 UTC, acmaccan commented on routes/categories.js
> + *                            $ref:' #components/schemes/categories'
Acá no te da error la comilla con el espacio?

2021-12-12 00:28 UTC, acmaccan requested changes
Bascur! La veo bien, te dejo una par de comentarios

2021-12-12 00:42 UTC, juanpabloch requested changes

2021-12-12 00:42 UTC, juanpabloch commented on routes/categories.js
> + *                            $ref:' #components/schemes/categories'
esta mal el espacio $ref:' #components/schemes/categories'
deberia ser asi: $ref: '#components/schemes/categories'
hay que coregir todos

2021-12-12 01:26 UTC, acmaccan commented on routes/categories.js
> + * schemes:
No veo este cambio, sigo viendo schemes. Puede ser?

2021-12-12 01:27 UTC, acmaccan reviewed
No veo el primer cambio, puede ser?

2021-12-12 12:46 UTC, juanpabloch approved these changes

2021-12-13 00:01 UTC, juanpabloch approved these changes

2021-12-13 00:13 UTC, acmaccan approved these changes

2021-12-13 00:14 UTC, AgustinTafura approved these changes
Perfecto!

2021-12-13 00:14 UTC, merged