OT107-89: Swagger Module
alkemyTech/OT107-Server pull request #103
Opened 2021-12-10 17:16 UTC by acmaccan

2021-12-10 20:16 UTC, SebasGalvan approved these changes
Todo 👌.

2021-12-11 14:50 UTC, juanpabloch approved these changes
buenisimo!!!!

2021-12-11 18:07 UTC, AgustinTafura requested changes

2021-12-11 18:07 UTC, AgustinTafura commented on modules/swagger.js
> +      servers: [
'servers' no debería estar al mismo nivel que 'openapi' e 'info'?

2021-12-11 18:25 UTC, juanpabloch requested changes

2021-12-11 18:25 UTC, juanpabloch commented on modules/swagger.js
> +      servers: [
si si tenes razon agus

2021-12-11 18:28 UTC, AgustinTafura commented on modules/swagger.js
> +      servers: [
Probé y funciona bien igual sin ese cambio

2021-12-11 18:55 UTC, acmaccan commented on modules/swagger.js
> +      servers: [
Buenísimo chicos. Sisi, funciona igual pero de todos modos lo modifiqué!

2021-12-11 20:37 UTC, AgustinTafura approved these changes
Buenisimo!

2021-12-11 21:31 UTC, fgarancini approved these changes

2021-12-11 23:31 UTC, juanpabloch approved these changes

2021-12-11 23:32 UTC, merged