OT107-86 - Agregar paginación a Novedades
alkemyTech/OT107-Server pull request #104
Opened 2021-12-10 18:44 UTC by as-ez

2021-12-10 19:27 UTC, AgustinTafura requested changes

2021-12-10 19:27 UTC, AgustinTafura commented on routes/news.js
> +  .get(authMiddleware.isAdmin, paginateMiddleware.pageValidation, newsController.getAll)
el authMiddleware debería ser el de isAuth

2021-12-10 19:54 UTC, as-ez commented on routes/news.js
> +  .get(authMiddleware.isAdmin, paginateMiddleware.pageValidation, newsController.getAll)
Gracias Agus

2021-12-10 20:08 UTC, MatiDalce approved these changes

2021-12-10 20:32 UTC, SebasGalvan approved these changes
Todo OK. 👍🏼

2021-12-11 16:40 UTC, AgustinTafura approved these changes
Perfecto!

2021-12-11 16:41 UTC, merged