OT107-91
alkemyTech/OT107-Server pull request #108
Opened 2021-12-10 20:16 UTC by fgarancini

2021-12-10 22:47 UTC, acmaccan commented on modules/swagger.js
> +const swaggerJsDoc = require('swagger-jsdoc');
Fran! sacaría todo lo del module de este branch y que quede solo el docs para evitar posibles conflictos con la branch del module

2021-12-10 22:47 UTC, acmaccan commented on routes/news.js
> + *     securyty:
Acá se pasó un typo

2021-12-10 22:47 UTC, acmaccan commented on routes/news.js
> + *     securyty:
Typo

2021-12-10 22:47 UTC, acmaccan commented on routes/news.js
> + *    securyty:
Y acá

2021-12-10 22:47 UTC, acmaccan commented on routes/news.js
> + *     securyty:
Y acá

2021-12-11 23:42 UTC, acmaccan approved these changes

2021-12-12 00:17 UTC, acmaccan commented on routes/news.js
> + *                type: array
Fran, falta indentación en type e item

2021-12-12 00:18 UTC, acmaccan commented on routes/news.js
> + *                 type: array
Acá también

2021-12-12 00:21 UTC, acmaccan commented on routes/news.js
> + *                 type: array
Acá

2021-12-12 00:22 UTC, acmaccan commented on routes/news.js
> + *                $ref:'#components/schemes/news'
Fran, fijate en todos los $ref, va schemas en vez de schemes.

2021-12-12 00:23 UTC, acmaccan requested changes
Fran, te dejo algunos comments

2021-12-12 23:59 UTC, juanpabloch approved these changes

2021-12-13 00:01 UTC, acmaccan approved these changes

2021-12-13 00:14 UTC, Bascur approved these changes

2021-12-13 00:14 UTC, merged