OT107-102: Testimonials Testing
alkemyTech/OT107-Server pull request #111
Opened 2021-12-15 23:14 UTC by acmaccan

- Fixes for Testimonial entity:
  - Seeder
  - Controller
  - Service
  - Middle

- Testimonial Testing

2021-12-16 13:53 UTC, acmaccan commented on controllers/testimonials.js
> +      message,
Lo traigo así porque trae las timestamps y me parece que sin eso se ve mejor.

2021-12-16 16:02 UTC, acmaccan commented on controllers/testimonials.js
> +    res.status(200).json({
Lo traigo así porque trae las timestamps y me parece que sin eso se ve mejor.

2021-12-16 19:31 UTC, juanpabloch approved these changes

2021-12-16 21:14 UTC, AgustinTafura approved these changes

2021-12-19 21:57 UTC, manuelfrancisco requested changes

2021-12-19 21:57 UTC, manuelfrancisco commented on test/testimonials.js
> +          response.should.have.status(400);
De por sí no veo este test necesario, pero si no se encuentra un recurso de la API debería devolver un 404

2021-12-19 21:57 UTC, manuelfrancisco commented on test/testimonials.js
> +    it('It should return testimonial by its id', (done) => {
Los tests de getById los pondría en otro describe

2021-12-22 21:28 UTC, as-ez approved these changes

2021-12-23 13:14 UTC, acmaccan commented on test/testimonials.js
> +          response.should.have.status(400);
Listo este cambio

2021-12-23 13:43 UTC, acmaccan reviewed
Ok cambios!

2021-12-23 21:22 UTC, closed without merging