Ot107 107 - Test: Endpoints /categories 🤞
alkemyTech/OT107-Server pull request #114
Opened 2021-12-16 23:08 UTC by SebasGalvan

2021-12-17 13:48 UTC, juanpabloch approved these changes

2021-12-17 19:50 UTC, AgustinTafura approved these changes

2021-12-17 20:00 UTC, acmaccan approved these changes
Espectacular Sebas!

2021-12-18 23:59 UTC, manuelfrancisco requested changes

2021-12-18 23:59 UTC, manuelfrancisco commented on test/categories.js
> +    describe('GET /categorie', () => {
Todos tests del enpoint de GET categories los metería en un solo describe

2021-12-18 23:59 UTC, manuelfrancisco commented on test/categories.js
> +    describe('Insert a category', () => {
Te faltarían casos para testear los caminos con error

2021-12-18 23:59 UTC, manuelfrancisco commented on test/categories.js
> +    describe('UPDATE the name of category with ID = 2', () => {
Te faltarían casos para testear los caminos con error

2021-12-23 19:45 UTC, as-ez approved these changes

2021-12-23 22:12 UTC, closed without merging