OT107-107 Test Categories
alkemyTech/OT107-Server pull request #123
Opened 2021-12-23 22:53 UTC by SebasGalvan

2021-12-25 21:26 UTC, as-ez approved these changes

2021-12-27 21:37 UTC, fgarancini approved these changes

2021-12-28 18:17 UTC, AgustinTafura commented on test/categories.js
> +          res.should.have.status(401);
el middleware isAdmin devuelve error status 400. Aunque deberíamos debatir si optamos con cambiar el middleware A 401 con "access denied" o cambiar los test.

2021-12-28 18:36 UTC, AgustinTafura requested changes
En todos los test con [invalidToken] como el token enviado es uno que ya expiró el error que devuelve es 400 corresponden al middleware isAdmin. Habría que corregirlo.

Salvo el de la linea 46, que utiliza el middleware isAuth y devuelve un error 401 y lo tenes OK.

2022-01-04 21:34 UTC, AgustinTafura approved these changes

2022-01-04 21:56 UTC, merged