107-96
alkemyTech/OT107-Server pull request #127
Opened 2022-01-01 19:30 UTC by MatiDalce

2022-01-02 15:06 UTC, AgustinTafura requested changes

2022-01-02 15:06 UTC, AgustinTafura commented on test/members.js
> +          res.body.should.have.property('countMembers');
Debería ser 'count' la propiedad que brinda la respuesta.

2022-01-02 15:06 UTC, AgustinTafura commented on test/members.js
> +          .get('/members?page=')
si se incluye el parametro page sin ningun valor, devuelve error y la respuesta esperada debería ser un 400 (como ocurre en éste caso).

Para que devuelva la pagina 1 como describe ésta prueba, no deberias pasarle el parametro  page ( debería quedarte .get('/memebers')

2022-01-02 15:06 UTC, AgustinTafura commented on test/members.js
> +            response.should.have.status(500);
el status esperado para este caso deberia ser un 400, como lo indica el middleware pageValidation para los casos que el valor de page es menor a 1.

2022-01-03 12:08 UTC, AgustinTafura approved these changes
Perfecto Mati!

2022-01-04 21:26 UTC, acmaccan approved these changes

2022-01-04 21:27 UTC, SebasGalvan approved these changes

2022-01-04 21:59 UTC, merged