OT107-41 Endpoint Listado de Categorías
alkemyTech/OT107-Server pull request #15
Opened 2021-11-24 18:30 UTC by SebasGalvan

2021-11-25 20:42 UTC, manuelfrancisco requested changes

2021-11-25 20:42 UTC, manuelfrancisco commented on repositories/categories.js
> +const category  = require('../models/index').categories;
definimos como práctica hacer require de todo y consumir lo que corresponda. En este caso sería algo así
`const db = require('../models');`
`db.Categories`

2021-11-25 20:42 UTC, manuelfrancisco commented on routes/categories.js
> +router.get('/', async function(req, res, next) {
La función que está en el EP debería estar en un controller

2021-11-26 12:39 UTC, SebasGalvan commented on routes/categories.js
> +router.get('/', async function(req, res, next) {
Listo Manu ya realicé los cambios que me pediste.

2021-11-26 19:53 UTC, SebasGalvan reviewed
Endpoint : categories listo

2021-11-28 19:31 UTC, manuelfrancisco requested changes

2021-11-28 19:31 UTC, manuelfrancisco commented on routes/categories.js
> +router.get('/', categoriesController.getAll);
tiene que validar usuario administrador

2021-11-28 20:09 UTC, manuelfrancisco approved these changes

2021-11-28 20:13 UTC, merged