Ot107 103
alkemyTech/OT107-Server pull request #16
Opened 2021-11-24 19:45 UTC by AgustinTafura

NEWS

+ Endpoint getAll
+ middleware isAdmin structure

2021-11-25 20:51 UTC, manuelfrancisco requested changes

2021-11-25 20:51 UTC, manuelfrancisco commented on repositories/news.js
> +const {News} = require('../models/index')
definimos como buena práctica importar todo el modelo completo y consumir lo necesario, por ejemplo algo así:
`const db = require('../models');`
`db.News`

2021-11-25 20:51 UTC, manuelfrancisco commented on routes/news.js
> +router.route('/')
porfa dejá sólo la ruta que corresponde a la funcionalidad

2021-11-25 20:51 UTC, manuelfrancisco commented on controllers/news.js
> +const serviceNews  = require('../services/news')
newsService

2021-11-25 20:51 UTC, manuelfrancisco commented on middlewares/auth.js
> +const isAdmin = (req,res,next) => {
esto está en otra funcionalidad, eliminalo y asumí que ya existe. Para probar que el endpoint de tu tarea funciona está bien incluirlo para que no te pinche, pero cuando se terminan las pruebas hay que sacarlo.

2021-11-26 03:39 UTC, AgustinTafura commented on repositories/news.js
> +const {News} = require('../models/index')
actualizado segun comentarios

2021-11-26 03:39 UTC, AgustinTafura commented on routes/news.js
> +router.route('/')
actualizado segun comentarios

2021-11-26 03:39 UTC, AgustinTafura commented on controllers/news.js
> +const serviceNews  = require('../services/news')
actualizado segun comentarios

2021-11-26 03:39 UTC, AgustinTafura commented on middlewares/auth.js
> +const isAdmin = (req,res,next) => {
actualizado segun comentarios

2021-11-27 22:17 UTC, manuelfrancisco approved these changes

2021-11-28 16:47 UTC, merged