Ot107 27
alkemyTech/OT107-Server pull request #17
Opened 2021-11-24 20:18 UTC by AgustinTafura

Middleware/auth 

+ isAdmin funcionality

2021-11-25 21:01 UTC, manuelfrancisco requested changes

2021-11-25 21:01 UTC, manuelfrancisco commented on middlewares/auth.js
> +    const adminRoleId = await roleService.getAdminRoleId() // should be include this funcionality in services/roles ?
No, lo que te recomiendo es que agregues el Id de rol admin en el config y lo consumas directamente sin llamar al servicio de roles.

2021-11-25 21:01 UTC, manuelfrancisco commented on middlewares/auth.js
> +        if (user.roleId !== adminRoleId) return res.status(401).json({ error: 'Access denied' })
Confirmá con Juan Pablo si el objeto que guarda el token tiene el campo roleId, y si no lo tiene pónganse de acuerdo en el grupo a ver quién lo guarda (sería en el endpoint de register)

2021-11-26 02:53 UTC, AgustinTafura commented on middlewares/auth.js
> +    const adminRoleId = await roleService.getAdminRoleId() // should be include this funcionality in services/roles ?
Finalmente se decidió por utilizar la funcion getIdByName(), creada en services/roles.js

2021-11-26 02:53 UTC, AgustinTafura commented on middlewares/auth.js
> +        if (user.roleId !== adminRoleId) return res.status(401).json({ error: 'Access denied' })
Se coordinó con el encargado del enpoint de registro que tenga en cuenta el RoleId

2021-11-27 22:34 UTC, manuelfrancisco approved these changes

2021-11-27 22:35 UTC, manuelfrancisco approved these changes

2021-11-28 16:27 UTC, merged