Ot107 105
alkemyTech/OT107-Server pull request #20
Opened 2021-11-24 22:10 UTC by Bascur

2021-11-25 21:05 UTC, manuelfrancisco requested changes

2021-11-25 21:05 UTC, manuelfrancisco commented on controllers/activities.js
> +const activitesService = require('../services/activities');
dice activites

2021-11-25 21:05 UTC, manuelfrancisco commented on repositories/activities.js
> +const activity = require('../models/index').activities;
convenimos como buena práctica importar el modelo completo y usar lo que corresponda, podría ser algo así:
`const db = require('../models');`
`db.Activities`

2021-11-25 21:05 UTC, manuelfrancisco commented on routes/activities.js
> +const users = require('../middleware/users');
usersMiddleware

2021-11-25 21:05 UTC, manuelfrancisco commented on routes/activities.js
> +router.get('/', users.admin, activitiesController.getAll);
confirmá cómo se llama el método del middleware

2021-11-26 00:11 UTC, Bascur commented on controllers/activities.js
> +const activitesService = require('../services/activities');
const activitiesService = require('../services/activities');

2021-11-26 00:11 UTC, Bascur commented on repositories/activities.js
> +const activity = require('../models/index').activities;
const db = require('../models');

const data = await db.activities.findAll();

2021-11-26 00:11 UTC, Bascur commented on routes/activities.js
> +const users = require('../middleware/users');
const usersMiddleware = require('../middleware/auth');

2021-11-26 00:12 UTC, Bascur commented on routes/activities.js
> +router.get('/', users.admin, activitiesController.getAll);
const usersMiddleware = require('../middleware/auth');

router.get('/',usersMiddleware.isAdmin, activitiesController.getAll);

2021-11-27 22:48 UTC, manuelfrancisco approved these changes

2021-11-28 23:38 UTC, merged