OT107-34 - Middleware de Ownership.
alkemyTech/OT107-Server pull request #23
Opened 2021-11-25 18:34 UTC by SebasGalvan

2021-11-25 21:46 UTC, manuelfrancisco requested changes

2021-11-25 21:46 UTC, manuelfrancisco commented on middlewares/auth.js
> +const decodeUserToken = (token) => {
estos dos métodos (decodeUserToken verifyToken) y  no tienen sentido para mí que estén acá

2021-11-25 21:46 UTC, manuelfrancisco commented on middlewares/auth.js
> +		if (!role) {
Este error debería darlo el service

2021-11-25 21:46 UTC, manuelfrancisco commented on middlewares/auth.js
> +const checkOwnerPermissions = async (req, res, next) => {
ya que estamos, le llamaría isOwnUser

2021-11-26 12:43 UTC, SebasGalvan reviewed
Listo Manu ya realicé los cambios que me pediste.
> Cree un servicio por fuera del middleware
> Agregue el repo y servicio de roles para poder usarlo (getByName).

2021-11-26 19:56 UTC, SebasGalvan reviewed
OT107-34 -Middleware de Ownership listo

2021-11-26 21:27 UTC, SebasGalvan reviewed
OT107-34 -Middleware de Ownership 

Ahora si, no tenia sentido mantener es funcionalidad en un archivo aparte.

2021-11-28 16:58 UTC, SebasGalvan reviewed
OT107-34 - Middleware de Ownership.

2021-11-28 19:33 UTC, manuelfrancisco approved these changes

2021-11-28 19:33 UTC, merged