OT107 25 - Endpoint de autenticación
alkemyTech/OT107-Server pull request #27
Opened 2021-11-26 00:52 UTC by as-ez

2021-11-27 23:11 UTC, manuelfrancisco requested changes

2021-11-27 23:11 UTC, manuelfrancisco commented on middlewares/auth.js
> +const loginUsersValidator = router.post('/login', [
Acá no hay que hacer una request de ningún tipo, acá se llega por la propia request

2021-11-27 23:11 UTC, manuelfrancisco commented on routes/testimonials.js
> +router.get('/', testimonialsController.getAll);
Este endpoint no tenías que tocarlo, deshacé los cambios o hacete un merge de dev

2021-11-27 23:11 UTC, manuelfrancisco commented on controllers/contacts.js
> +const getAll = async (req, res, next) => {
Este controller tampoco había que tocarlo

2021-11-27 23:11 UTC, manuelfrancisco commented on routes/index.js
> +var express = require('express');
Esto no sé por qué lo cambiaste por var, siempre es preferible usar const o let

2021-11-27 23:11 UTC, manuelfrancisco commented on services/contacts.js
> +const getAll = async() => {
Este service no había que tocarlo

2021-11-27 23:11 UTC, manuelfrancisco commented on routes/auth.js
> +router.post('/login', loginMiddelware.login, authController.login);
la función login no existe en el authMiddleware

2021-11-27 23:11 UTC, manuelfrancisco commented on routes/auth.js
> +const loginMiddelware = require('../middlewares/auth');
preferible que se llame authMiddleware

2021-11-27 23:11 UTC, manuelfrancisco commented on repositories/contacts.js
> +const getAll = async() => {
Este repo tampoco había que tocarlo

2021-11-28 17:57 UTC, as-ez commented
Mnau creo que estamos teniendo conflictos con el package-lock.json, se agrega al commit aunque esté en el .gitignore.

Busque alguna solución y encontré esto:

You need to remove it from your repo (git rm package-lock.json) in order for git to stop tracking it.

.gitignore only works for untracked files. If you have a tracked file that is also in your .gitignore, the fact that the file is tracked overrides the fact that it is also in .gitignore.

2021-11-28 19:47 UTC, manuelfrancisco requested changes

2021-11-28 19:47 UTC, manuelfrancisco commented on controllers/auth.js
> +        if(usersService.validPassword(req.body.password, user.password)){
de esta validación se encarga el service

2021-11-29 15:02 UTC, manuelfrancisco approved these changes

2021-11-29 15:03 UTC, manuelfrancisco commented
Hay cosas que no quedaron como habíamos hablado pero lo apruebo para que pase de una vez el punto sino vamos a seguir acumulando conflictos

2021-11-29 16:58 UTC, merged