Ot107 24
alkemyTech/OT107-Server pull request #29
Opened 2021-11-26 06:11 UTC by Bascur

2021-11-27 23:25 UTC, manuelfrancisco requested changes

2021-11-27 23:25 UTC, manuelfrancisco commented on middleware/auth.js
> +const registerUsersValidator = router.post('/', [
No hay que definir la ruta acá, se debe usar este método justamente cuando se llama para validar la entrada

2021-11-27 23:25 UTC, manuelfrancisco commented on routes/auth.js
> +const registerUsersValidator = require('../middleware/auth');
preferible que se llame authMiddleware

2021-11-27 23:58 UTC, Bascur commented on routes/auth.js
> +const registerUsersValidator = require('../middleware/auth');
const authMiddleware = require('../middleware/auth');

2021-11-28 01:53 UTC, Bascur commented on middleware/auth.js
> +const registerUsersValidator = router.post('/', [
Resolved

2021-11-28 02:18 UTC, closed without merging