Ot107 63
alkemyTech/OT107-Server pull request #3
Opened 2021-11-23 22:16 UTC by as-ez

2021-11-25 21:38 UTC, manuelfrancisco requested changes

2021-11-25 21:38 UTC, manuelfrancisco commented on controllers/contacts.js
> +const contactsService = require('../services/contacts.js');
los require sin ".js"

2021-11-25 21:38 UTC, manuelfrancisco commented on models/index.js
> +	.readdirSync(__dirname)
este archivo revertilo, no sé por qué todos estos espacios

2021-11-25 21:38 UTC, manuelfrancisco commented on routes/contacts.js
> +const isAdmin = require('../middleware/auth');
este middleware va a tener más métodos aparte del isAdmin, te convendría guardarlo en una variable que se llame authMiddleware

2021-11-25 21:38 UTC, manuelfrancisco commented on routes/contacts.js
> +router.get('/', isAdmin ,contactsController.getAll);
acá consumirías el middleware así:
`authMiddleware.isAdmin`
pensá que al hacer el require estás guardandote todo el objeto, el código que tenés es como si estuvieras haciendo un require de una función pero es un objeto que tiene una función

2021-11-25 21:38 UTC, manuelfrancisco commented on services/contacts.js
> +const contactsRepositorie = require('../repositories/contacts');
Repository

2021-11-25 22:15 UTC, as-ez commented on models/index.js
> +	.readdirSync(__dirname)
fue probando el autosave del eslint. ya pude solucionarlo y revertirlo

2021-11-27 22:08 UTC, manuelfrancisco approved these changes

2021-11-27 22:08 UTC, merged