Demo fixes2
alkemyTech/OT107-Server pull request #38
Opened 2021-11-30 15:02 UTC by acmaccan

- Format data response
- Testimonial model y seeder
- Users seeder
- Postman documentation

2021-11-30 20:17 UTC, manuelfrancisco requested changes

2021-11-30 20:17 UTC, manuelfrancisco commented on repositories/register.js
> +  body.password = bcrypt.hashSync(body.password, 10);
Este repositorio no debería existir, esto viene a ser el create del repo de users. Y además la implementación de bycrypt es responsabilidad del service.

2021-11-30 20:17 UTC, manuelfrancisco commented on middlewares/auth.js
> +    const userToken = req.header('auth-token');
Estandarizar la consumición del token

2021-11-30 20:17 UTC, manuelfrancisco commented on repositories/roles.js
> +  const roleInfo = {
Esta transformación debe formar parte del service

2021-11-30 20:17 UTC, manuelfrancisco commented on routes/activities.js
> +const usersMiddleware = require('../middlewares/auth');
tiene más sentido authMiddleware

2021-11-30 20:17 UTC, manuelfrancisco commented on services/news.js
> +  } catch (e) {
este catch está de más, como cualquier catch en el service

2021-11-30 23:03 UTC, Bascur commented on repositories/register.js
> +  body.password = bcrypt.hashSync(body.password, 10);
Solucionado

2021-12-01 02:28 UTC, manuelfrancisco approved these changes

2021-12-01 02:28 UTC, merged