Ot107 47
alkemyTech/OT107-Server pull request #41
Opened 2021-12-01 04:08 UTC by AgustinTafura

+ POST /news => add endpoint

+ middleware/news=> newsInputValidation 

+ modules/filesHandler: => isImage

+ repository/category=> add getByName 

+ service/news => assignment news categoryId from Categories by default

2021-12-01 15:10 UTC, manuelfrancisco requested changes

2021-12-01 15:10 UTC, manuelfrancisco commented on controllers/news.js
> +    if (!news) throw new Error('bad request');
Esta validación no me parece correcta, si no hay novedades debería devolver una lista vacía que es lo que devuelve la BD.
Igual como dato aparte, si estuviera bien validar iría en el service.

2021-12-01 15:10 UTC, manuelfrancisco commented on controllers/news.js
> +    if (!news) throw new Error('bad request');
En el service esta validación

2021-12-01 15:10 UTC, manuelfrancisco commented on controllers/news.js
> +    res.sendStatus(204);
Devolvería 200 y la novedad creada, que dicho sea de paso el singular de news es novelty
Quedaría algo así:
`res.status(200).json(novelty);`

2021-12-01 15:10 UTC, manuelfrancisco commented on middlewares/auth.js
> +    if (req.body.email) {
esta validación la haría a nivel service

2021-12-01 15:10 UTC, manuelfrancisco commented on repositories/news.js
> +  try {
en los repos no hacer try catch, que se encargue el controller

2021-12-01 15:10 UTC, manuelfrancisco commented on routes/users.js
> +<<<<<<< HEAD
Te quedaron conflictos sin resolver acá

2021-12-01 15:10 UTC, manuelfrancisco commented on services/news.js
> +  const validData = data;
no veo la necesidad de asignar esto a otra variable

2021-12-01 17:01 UTC, AgustinTafura commented on repositories/news.js
> +  try {
Eliminados try-catch de service

2021-12-01 17:01 UTC, AgustinTafura commented on controllers/news.js
> +    res.sendStatus(204);
Corregido con la solución propuesta

2021-12-01 17:01 UTC, AgustinTafura commented on controllers/news.js
> +    if (!news) throw new Error('bad request');
Validacion eliminada de controller y agregada al service

2021-12-01 17:01 UTC, AgustinTafura commented on controllers/news.js
> +    if (!news) throw new Error('bad request');
Validación eliminada del controller

2021-12-01 17:02 UTC, AgustinTafura commented on routes/users.js
> +<<<<<<< HEAD
Conflictos resueltos

2021-12-01 17:15 UTC, AgustinTafura commented on services/news.js
> +  const validData = data;
Lo habia puesto así por propuesta de ESLint ('no-param-reassign').
Corregido según solución propuesta.

2021-12-01 17:45 UTC, AgustinTafura commented on middlewares/auth.js
> +    if (req.body.email) {
La validación está duplicada, la misma ya se encuentra en el service/user. 
Se eliminó del middleware

2021-12-02 02:42 UTC, manuelfrancisco approved these changes

2021-12-02 14:13 UTC, merged