OT107-69 Create Testimonials
alkemyTech/OT107-Server pull request #43
Opened 2021-12-01 13:44 UTC by acmaccan

Create testimonials:
Route POST /testimonials
isAdmin
Input validation Middleware
Create Testimonial Controller
Create Testimonial Service
Create Testimonial Repository
Postman documentation: Ok and validation errors responses

2021-12-01 15:17 UTC, manuelfrancisco requested changes

2021-12-01 15:17 UTC, manuelfrancisco commented on repositories/testimonials.js
> +  const { name, image, content } = body;
el parámetro debería llegar al repo listo para el insert

2021-12-01 15:17 UTC, manuelfrancisco commented on routes/testimonials.js
> +const middleTestimonials = require('../middlewares/testimonials');
testimonialsMiddleware

2021-12-01 16:59 UTC, acmaccan commented on routes/testimonials.js
> +const middleTestimonials = require('../middlewares/testimonials');
Ni mi propia convención sigo de un renglón a otro! Que aparateada me mandé

2021-12-01 17:11 UTC, acmaccan commented on repositories/testimonials.js
> +  const { name, image, content } = body;
Listo!

2021-12-02 15:54 UTC, acmaccan commented
Manu, te dejo los cambios que hablamos ayer sobre el validator y los pasos de parámetros.

2021-12-02 23:31 UTC, manuelfrancisco approved these changes

2021-12-02 23:31 UTC, merged