Post activities & middleware
alkemyTech/OT107-Server pull request #47
Opened 2021-12-01 15:35 UTC by Bascur

2021-12-02 23:47 UTC, manuelfrancisco requested changes

2021-12-02 23:47 UTC, manuelfrancisco commented on controllers/activities.js
> +    const activities = await activitiesService.create(req.body);
Es una sola activity lo que te devuelve, y si querés controlar los campos que se devuelven que sea en el service.

2021-12-02 23:47 UTC, manuelfrancisco commented on middlewares/activities.js
> +  check('name', 'Activity Name Required').not().isEmpty(),
Creo que acá falta un .required() o .exists() o algo así para validar que venga obligatoriamente

2021-12-02 23:47 UTC, manuelfrancisco commented on repositories/activities.js
> +  const data = await db.activities.create(body);
Hay que renombrar el modelo a Activities con la primera mayúscula

2021-12-02 23:47 UTC, manuelfrancisco commented on routes/activities.js
> +router.post('/', (authMiddleware.isAdmin, activitiesMioddleware.activitiesInputValidation), activitiesController.create);
No hacen falta los paréntesis

2021-12-03 00:27 UTC, Bascur commented on middlewares/activities.js
> +  check('name', 'Activity Name Required').not().isEmpty(),
A menos que no este contemplando algo, con estas validaciones deberia chequear tanto si el campo esta vacio como obligar a que tengas que pasar un dato.

En la docu del validator no figura ninguna opcion que sea especificamente para que venga. required o exist no figuran

2021-12-03 00:28 UTC, Bascur commented on repositories/activities.js
> +  const data = await db.activities.create(body);
modelName: 'Activities',
const data = await db.Activities.findAll();

2021-12-03 00:29 UTC, Bascur commented on routes/activities.js
> +router.post('/', (authMiddleware.isAdmin, activitiesMioddleware.activitiesInputValidation), activitiesController.create);
router.post('/', authMiddleware.isAdmin, activitiesMioddleware.activitiesInputValidation, activitiesController.create);

2021-12-03 00:42 UTC, Bascur commented on controllers/activities.js
> +    const activities = await activitiesService.create(req.body);
const activity = await activitiesService.create(req.body);
    res.status(200).json(
      activity
    );

2021-12-03 12:36 UTC, manuelfrancisco approved these changes

2021-12-03 12:40 UTC, merged