OT107-70: Update Testimonials
alkemyTech/OT107-Server pull request #51
Opened 2021-12-01 23:13 UTC by acmaccan

Update testimonials: 
Route PUT /testimonials
isAdmin
Controller
Service
Repository
Postman documentation - Ok and error response

2021-12-02 02:20 UTC, manuelfrancisco requested changes

2021-12-02 02:20 UTC, manuelfrancisco commented on controllers/testimonials.js
> +const create = async (req, res, next) => {
Eliminar el create de acá, no pertenece a esta funcionalidad

2021-12-02 02:20 UTC, manuelfrancisco commented on controllers/testimonials.js
> +    const testimonialId = await testimonialsService.getById(id);
Tanto la deconstrucción de objeto como la validación de si el testimonio existe deben realizarse en el service, debido a que son validaciones pertinentes al negocio y por tanto su responsabilidad.

2021-12-02 02:20 UTC, manuelfrancisco commented on controllers/testimonials.js
> +    await testimonialsService.update(id, name, image, content);
El update debería devolver el objeto actualizado

2021-12-02 02:20 UTC, manuelfrancisco commented on middlewares/testimonials.js
> +const { check, validationResult } = require('express-validator');
Este middleware no pertenece a esta funcionalidad

2021-12-02 02:20 UTC, manuelfrancisco commented on repositories/testimonials.js
> +const create = async (name, image, content) => {
No pertenece a la funcionalidad

2021-12-02 02:20 UTC, manuelfrancisco commented on repositories/testimonials.js
> +const update = async (id, name, image, content) => {
Recibir el objeto completo y no propiedades sueltas

2021-12-02 02:20 UTC, manuelfrancisco commented on services/testimonials.js
> +const update = async (id, name, image, content) => {
Recibir el objeto del body completo

2021-12-02 15:31 UTC, acmaccan commented on controllers/testimonials.js
> +const create = async (req, res, next) => {
Hecho!

2021-12-02 15:31 UTC, acmaccan commented on controllers/testimonials.js
> +    const testimonialId = await testimonialsService.getById(id);
Hecho!

2021-12-02 15:32 UTC, acmaccan commented on controllers/testimonials.js
> +    await testimonialsService.update(id, name, image, content);
Incluso, el error ese lo pasé al método getById, me pareció más apropiado. Si no es así, avisame y lo veo

2021-12-02 15:32 UTC, acmaccan commented on middlewares/testimonials.js
> +const { check, validationResult } = require('express-validator');
Hecho!

2021-12-02 15:33 UTC, acmaccan commented on repositories/testimonials.js
> +const create = async (name, image, content) => {
Hecho!

2021-12-02 15:33 UTC, acmaccan commented on repositories/testimonials.js
> +const update = async (id, name, image, content) => {
Modificado

2021-12-02 15:33 UTC, acmaccan commented on services/testimonials.js
> +const update = async (id, name, image, content) => {
Modificado

2021-12-02 15:56 UTC, acmaccan commented
Manu, te dejo los cambios que hablamos ayer. Incluso modifiqué algo más que no charlamos. Fijate que el error de que si el testimonial no existe ahora lo devuelve el getById, me parece más apropiado. Ayer estaba en el update.

2021-12-03 00:59 UTC, manuelfrancisco approved these changes

2021-12-03 01:52 UTC, merged