OT107-59: Create Slides
alkemyTech/OT107-Server pull request #84
Opened 2021-12-04 22:25 UTC by acmaccan

Create Slides
POST /slides
isAdmin
Upload image to S3
imageUrl from upload image to AWS S3
text
organizationId from config
lastOrder

2021-12-04 23:44 UTC, manuelfrancisco requested changes

2021-12-04 23:44 UTC, manuelfrancisco commented on services/slides.js
> +  const newSlide = {
acá yo haría:
`{
  ...body,
  image: uploadImage.Location,
  order: body.order || nextOrder
}`

2021-12-05 01:08 UTC, acmaccan commented on services/slides.js
> +  const newSlide = {
Oka, le estaba pasando el id de la organization a través de la variable config.idOrganization que estaba declarada en la config, creía que era mejor para que el usuario no le tuviera que pasar el parámetro 1 por body. Lo cambio y ahora queda del lado del usuario pasarle el id de la organization.

2021-12-05 15:39 UTC, manuelfrancisco approved these changes

2021-12-05 15:39 UTC, merged